### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by d** [d/bug-free-fortnight#10]
Even if it's just running `shellcheck`

**Comment by xinzweb** [comment]
Do you mean to have 'travis' running this whole scripts? Very good idea.

Then, maybe we don't need a separate PR pipeline then.

**Comment by d** [comment]
No. I just want to lint the Bash scripts to begin with. Running the whole script is inherently difficult and doesn't clearly indicate whether it's a script error or a GPDB error

**Comment by d** [comment]
Resolved by e02c2fc
