### ISSUE TITLE
Is that possible to just run ONE failed regression test?

### ISSUE THREAD

**Issue by xinzweb** [d/bug-free-fortnight#11]
Here is a scenario:
- I run the full ICG and ICB
- One test failed
- I want to repro just that one test failure instead of running the entire tests.

**Comment by d** [comment]
Yes you can. Do the following:
`streamline-master/uber.bash --interactive`
After building, it will stop at a friendly interactive shell, you then do (I'm using `int4` with ORCA as an example)
`env PGOPTIONS='-c optimizer' ./pg_regress int4`

Then when you exit that shell, the container should be cleaned up, and `regression.diffs` should be copied onto your host computer.
