### ISSUE TITLE
I want to remote debugging into dockers for my failed tests

### ISSUE THREAD

**Issue by xinzweb** [d/bug-free-fortnight#12]

**Comment by d** [comment]
Could you elaborate? Are you thinking of `gdbserver` or something? I'm gonna close this until you have more information. Feel free to re-open when you update the issue @xinzweb .

**Comment by xinzweb** [comment]
Yes, `gdbserver` related.

**Comment by d** [comment]
Xin can you edit the issue into a user story-style scenario to illustrate how this is useful, especially given that neither of us has a clue how to implement it?

**Comment by d** [comment]
Closing anything that's here for longer than 6 months. Issues is not used as an inventory.
