### ISSUE TITLE
How to control different build and run flavors?

### ISSUE THREAD

**Issue by xinzweb** [d/bug-free-fortnight#13]
- Build 32bit/64bit
- Build with/without GPORCA
- Build with/without CodeGen
- Run ICG with/without GPORCA
- Run ICB with/without GPORCA

**Comment by d** [comment]
Building with different "flavors" is explicitly deferred / not considered. Ideally one build should contain all features and we toggle them at runtime (case in point: ORCA and codegen).

To run ICG without orca, do this:
`uber.bash --no-optimizer`

To run bugbuster without orca, similarly do this:
`streamline-43/uber.bash --no-optimizer`

**Comment by d** [comment]
Thank you for opening an issue here @xinzweb I do feel this is a more appropriate space than the team channel before this project is ready
