### ISSUE TITLE
How to swap ORCA binary for 4.3?

### ISSUE THREAD

**Issue by d** [d/bug-free-fortnight#14]
Heard this question from @oarap today.
# askingforafriend

**Comment by d** [comment]
@oarap can you try running this:

```
tar xf /orca/bin_orca.tar -C /build/install/greenplum-db-devel
```

And then restart DB:

```
gpstop -ar
```

**Comment by xinzweb** [comment]
Shall we make it some kind of doc inside this repo?

Also, these are the scripts running inside the container, right?

**Comment by d** [comment]
1. Yes we should provide documentation.
2. No I don't consider swapping ORCA binary a "supported" thing yet:
   1. There is no guarantee swapping works: headers depended upon by the translator might have changed, so not rebuilding the translator will likely cause completely surprising runtime behavior.
   2. Rebuilding always works.
   3. The normal build flow takes about 34 seconds if you are not using the stupid whale (a.k.a. Docker for Mac beta).
   4. Which means we are trading correctness of our build for an expediency of less than 60 seconds. Is it worth it? I'd like to defer this decision.
3. No this is what you manually run inside `uber.bash --interactive`
