### ISSUE TITLE
Show Xerces, GPOS, or ORCA compilation output only when it fails

### ISSUE THREAD

**Issue by d** [d/bug-free-fortnight#15]
I am starting to feel there's too much noise in the output, especially considering that I get diminishing value out of the output: what do I get out of the quickly scrolling screen? The feeling that time is elapsing?

I have a few options to make this more quiet, but before even shaving this yak, I want to gather some feedback from you guys, @oarap @xinzweb and @hsyuan:
1. Do you feel strongly about this? Choose one out of three:
   - I hate it, it's so noisy!!!
   - I love it, noise gives me a good existential feeling!
   - Noise. Meh. C'est la vie
2. Am I the only one annoyed by the ORCA compilation output at the beginning of the build process?
3. If you find it valuable, can you leave a comment below and let me know what value you get out of the output
4. If you feel "meh", can you help me decide which improvement item gives you more value:
   1. debug build
   2. suppress ORCA output unless it fails

**Comment by oarap** [comment]
To be brief, I would wanna have the noisy output as an option such as
--debug but the default should be silent. It should always tell me if
something fails.

For 4 my answer is 1

**Comment by hsyuan** [comment]
2。
I don't hate it, I don't know what does the 3rd option mean. Only 2nd option left for me.
It is not a problem for me. So you can decide whatever you want.
