### ISSUE TITLE
Friendly message for deleting the container

### ISSUE THREAD

**Issue by d** [d/bug-free-fortnight#3]
After #1, the script will _not_ delete the container unless something fails before entering interactive shell. Maybe show a message about the command to delete the container?

**Comment by xinzweb** [comment]
Well, are you saying to show `docker rm` command to help people remove the unused containers? Maybe just point them to the docker document then?

**Comment by d** [comment]
Actually this is no longer an open issue given that you mostly have only two ways of consuming the script now:
1. `uber.bash`: this runs ICG and then self-destructs
2. `uber.bash --interactive` which stops after initializing a cluster, and giving you shell access, after which it self-destructs

In no normal case does the user ever need to run `docker rm` any more. I'm closing this issue.
