### ISSUE TITLE
Debug build support?

### ISSUE THREAD

**Issue by d** [d/bug-free-fortnight#6]
## User story

As a Greenplum database core maintainer,
I want to a consistent way to verify pull requests,
which gives me the same level of confidence as a forked CI pipeline would have given me

**Comment by xinzweb** [comment]
Hmm, would this solved by the PR pipeline at https://gporca.ci.pivotalci.info/pipelines/gpdb_pr

**Comment by d** [comment]
This is about testing ORCA change, so no.

**Comment by d** [comment]
Partially addressed by 1fe6c65615bc67cf071e57886c54cb93371221aa , where we added debug support for OSS build of gpdb master.

**Comment by d** [comment]
Addressed in 1fe6c65..c2c47eb
