### ISSUE TITLE
Run ICG without optimizer?

### ISSUE THREAD

**Issue by oarap** [d/bug-free-fortnight#8]
**Given** that Omer, an ORCA contributor is fixing a planner issues
**When** Omer runs `uber.bash --no-optimizer`
**Then** uber script should run `installcheck` without turning on optimizer.

**Comment by d** [comment]
I'm working on it

**Comment by d** [comment]
This should be resolved in fa202a9 , @oarap can you pull and try the following?
`streamline-master/uber.bash --no-optimizer`
and
`streamline-43/uber.bash --no-optimizer`

**Comment by d** [comment]
fixed in fa202a9
